void main() {
	pushi (ebp);
	move (esp,ebp);
	addi (-12,esp);
	storei(10,ind(ebp,-4));
	storei(5,ind(ebp,-12));
	storei(0,ind(ebp,-8));
l1:	loadi(ind(ebp,-12),eax);
	cmpi(0,eax);
	je(l2);
	loadi(ind(ebp,-4),eax);
	loadi(ind(ebp,-4),ebx);
	loadi(ind(ebp,-4),ecx);
	loadi(ind(ebp,-4),edx);
	loadi(ind(ebp,-4),edi);
	loadi(ind(ebp,-4),esi);
	pushi(eax);
	loadi(ind(ebp,-4),eax);
	pushi(ebx);
	loadi(ind(ebp,-4),ebx);
	pushi(ecx);
	loadi(ind(ebp,-4),ecx);
	pushi(edx);
	loadi(ind(ebp,-4),edx);
	addi(ecx,edx);
	addi(ebx,edx);
	addi(eax,edx);
	addi(esi,edx);
	addi(edi,edx);
	loadi(ind(esp),edi);
	popi(1);
	addi(edi,edx);
	loadi(ind(esp),ecx);
	popi(1);
	addi(ecx,edx);
	loadi(ind(esp),ebx);
	popi(1);
	addi(ebx,edx);
	loadi(ind(esp),eax);
	popi(1);
	addi(eax,edx);
	storei(edx,ind(ebp,-4));
	loadi(ind(ebp,-12),edx);
	move(1,eax);
	muli(-1,eax);
	addi(edx,eax);
	storei(eax,ind(ebp,-12));
	storei(1,ind(ebp,-8));
	j(l1);
l2:	loadi(ind(ebp,-4),eax);
	print_int(eax);
	print_string("\n");
	addi (12,esp);
	loadi (ind(esp),ebp);
	popi(1);
}

