void main() {
	pushi (ebp);
	move (esp,ebp);
	addi (-4,esp);
	loadi(ind(ebp,-4),eax);
	loadi(ind(ebp,-4),ebx);
	loadi(ind(ebp,-4),ecx);
	loadi(ind(ebp,-4),edx);
	loadi(ind(ebp,-4),edi);
	loadi(ind(ebp,-4),esi);
	pushi(eax);
	loadi(ind(ebp,-4),eax);
	pushi(ebx);
	loadi(ind(ebp,-4),ebx);
	pushi(ecx);
	loadi(ind(ebp,-4),ecx);
	pushi(edx);
	loadi(ind(ebp,-4),edx);
	addi(ecx,edx);
	addi(ebx,edx);
	addi(eax,edx);
	addi(esi,edx);
	addi(edi,edx);
	loadi(ind(esp),edi);
	popi(1);
	addi(edi,edx);
	loadi(ind(esp),ecx);
	popi(1);
	addi(ecx,edx);
	loadi(ind(esp),ebx);
	popi(1);
	addi(ebx,edx);
	loadi(ind(esp),eax);
	popi(1);
	addi(eax,edx);
	addi (4,esp);
	loadi (ind(esp),ebp);
	popi(1);
}

