void main() {
	pushi (ebp);
	move (esp,ebp);
	addi (-32,esp);
	storei(10,ind(ebp,-4));
	storei(5,ind(ebp,-12));
	storei(0,ind(ebp,-8));
l1:	loadi(ind(ebp,-12),eax);
	cmpi(0,eax);
	je(l2);
	loadi(ind(ebp,-4),eax);
	muli(10,eax);
	storei(eax,ind(ebp,-4));
	loadi(ind(ebp,-12),eax);
	move(1,ebx);
	muli(-1,ebx);
	addi(eax,ebx);
	storei(ebx,ind(ebp,-12));
	loadi(ind(ebp,-4),ebx);
	loadi(ind(ebp,-12),eax);
	muli(4,eax);
	addi(-32,eax);
	storei(ebx,ind(ebp,eax));
	storei(1,ind(ebp,-8));
	j(l1);
l2:	storei(5,ind(ebp,-12));
	storei(0,ind(ebp,-8));
l3:	loadi(ind(ebp,-12),eax);
	cmpi(0,eax);
	je(l4);
	loadi(ind(ebp,-12),eax);
	move(1,ebx);
	muli(-1,ebx);
	addi(eax,ebx);
	storei(ebx,ind(ebp,-12));
	loadi(ind(ebp,-12),ebx);
	muli(4,ebx);
	addi(-32,ebx);
	loadi(ind(ebp,ebx),ebx);
	print_int(ebx);
	print_string(" ");
	storei(1,ind(ebp,-8));
	j(l3);
l4:	print_string("\n");
	storei(0,ind(ebp,-8));
l5:	loadi(ind(ebp,-8),eax);
	move(10,ebx);
	cmpi(eax,ebx);
	jl(l6);
	move(0,ebx);
	j(l7);
l6:	move(1,ebx);
l7:	cmpi(0,ebx);
	je(l8);
	loadi(ind(ebp,-8),ebx);
	muli(3,ebx);
	print_int(ebx);
	loadi(ind(ebp,-8),ebx);
	move(1,eax);
	addi(ebx,eax);
	storei(eax,ind(ebp,-8));
	j(l5);
l8:	print_string("\n");
	loadi (ind(ebp),ebp);
	addi (32,esp);
	popi(1);
}

